version : "3.8"
services:
  app:
    build: .
    ports:
      - "7070:7070"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER : harru
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: BloodBuddy
    ports:
      - 3308:3306
